export const dataTemp = [
    { cat: "AGM", soal: "Saya suka mempelajari kisah teladan tokoh agama", bobot: 30.0 },
    { cat: "AGM", soal: "Saya suka mendengarkan lagu-lagu religi", bobot: 2.5 },
    { cat: "AGM", soal: "Saya suka mempelajari kitab suci", bobot: 22.5 },
    { cat: "AGM", soal: "Saya suka mengisi waktu luang dengan membaca buku keagamaan", bobot: 5.0 },
    { cat: "AGM", soal: "Saya tertarik untuk menyimak ceramah agama", bobot: 5.0 },
    { cat: "AGM", soal: "Saya suka mempelajari doa-doa", bobot: 7.5 },
    { cat: "AGM", soal: "Saya suka mendalami makna ibadah", bobot: 10.0 },
    { cat: "AGM", soal: "Saya suka mengikuti kegiatan di tempat ibadah", bobot: 2.5 },
    { cat: "AGM", soal: "Saya suka menyampaikan pesan-pesan keagamaan", bobot: 15.0 },
    { cat: "MTK", soal: "Saya suka melakukan kegiatan ukur mengukur", bobot: 15.0 },
    { cat: "MTK", soal: "Saya suka merancangkan kegiatan berdasarkan ketepatan waktu", bobot: 10.0 },
    { cat: "MTK", soal: "Saya suka menggunakan hitungan, dalam memprediksi sesuatu", bobot: 10.0 },
    { cat: "MTK", soal: "Saya menyukai grafik", bobot: 30.0 },
    { cat: "MTK", soal: "Saya menyukai penjelasan dalam bentuk angka", bobot: 5.0 },
    { cat: "MTK", soal: "Saya suka menyelesaikan soal hitungan dengan menggunakan logika", bobot: 15.0 },
    { cat: "MTK", soal: "Saya suka membaca angka secara benar", bobot: 5.0 },
    { cat: "MTK", soal: "Saya suka membaca secara teliti terhadap soal hitungan", bobot: 10.0 },
    { cat: "IPA", soal: "Saya suka mengamati peristiwa alam", bobot: 15.0 },
    { cat: "IPA", soal: "Saya suka dengan kegiatan ilmiah", bobot: 5.0 },
    { cat: "IPA", soal: "Saya suka melakukan percobaan ilmiah", bobot: 30.0 },
    { cat: "IPA", soal: "Saya suka mendalami tentang proses kimiawi suatu zat", bobot: 7.5 },
    { cat: "IPA", soal: "Saya suka mengamati pertumbuhan tanaman", bobot: 7.5 },
    { cat: "IPA", soal: "Saya suka mengamati kandungan zat sebuah produk", bobot: 5.0 },
    { cat: "IPA", soal: "Saya suka mencoba merakit alat percobaan ilmiah", bobot: 10.0 },
    { cat: "IPA", soal: "Saya suka diskusi tentang kejadian alam", bobot: 15.0 },
    { cat: "IPA", soal: "Saya suka mengumpulkan berita tentang peristiwa alam", bobot: 5.0 },
    { cat: "IPS", soal: "Saya suka mempelajari peta", bobot: 10.0 },
    { cat: "IPS", soal: "Saya suka membaca buku-buku sejarah", bobot: 30.0 },
    { cat: "IPS", soal: "Saya suka mempelajari benda-benda peninggalan sejarah", bobot: 5.0 },
    { cat: "IPS", soal: "Saya suka mempelajari budaya", bobot: 5.0 },
    { cat: "IPS", soal: "Saya suka mempelajari kehidupan sosial", bobot: 40.0 },
    { cat: "IPS", soal: "Saya suka mempelajari tentang kegiatan ekonomi", bobot: 10.0 },
    { cat: "BDB", soal: "Saya suka menyimak cerita", bobot: 5.0 },
    { cat: "BDB", soal: "Saya suka bercerita", bobot: 15.0 },
    { cat: "BDB", soal: "saya suka berdiskusi tentang kebahasaan", bobot: 30.0 },
    { cat: "BDB", soal: "Saya suka bermain peran", bobot: 5.0 },
    { cat: "BDB", soal: "Saya suka membaca buku cerita Saya suka menulis karya sastra", bobot: 30.0 },
    { cat: "BDB", soal: "Saya suka menulis buku harian", bobot: 5.0 },
    { cat: "BDB", soal: "Saya suka berpidato", bobot: 10.0 },
    { cat: "TDR", soal: "Saya suka menggambar bangunan", bobot: 10.0 },
    { cat: "TDR", soal: "Saya suka merakit alat elektronik", bobot: 30.0 },
    { cat: "TDR", soal: "Saya suka menuangkan ide ke dalam hasil teknologi", bobot: 5.0 },
    { cat: "TDR", soal: "Saya suka mencermati cara kerja alat-alat teknologi", bobot: 10.0 },
    { cat: "TDR", soal: "Saya suka mendaur ulang barang yang tidak terpakai", bobot: 15.0 },
    { cat: "TDR", soal: "Saya suka memecahkan masalah yang berkaitan dengan teknik", bobot: 30.0 },
    { cat: "TIK", soal: "Saya suka menyusun diagram alur", bobot: 15.0 },
    { cat: "TIK", soal: "Saya suka mempelajari program komputer", bobot: 20.0 },
    { cat: "TIK", soal: "Saya suka menggunakan program aplikasi komputer", bobot: 20.0 },
    { cat: "TIK", soal: "Saya suka menggunakan media komunikasi untuk belajar", bobot: 10.0 },
    { cat: "TIK", soal: "Saya suka menulis di media sosial atau blog", bobot: 5.0 },
    { cat: "TIK", soal: "Saya suka mengikuti perkembangan TIK", bobot: 30.0 },
    { cat: "KES", soal: "Saya menyukai kegiatan P3K", bobot: 30.0 },
    { cat: "KES", soal: "Saya suka membaca keguanaan obat", bobot: 5.0 },
    { cat: "KES", soal: "Saya suka mengenali jenis tumbuhan yang mengandung khasiat obat", bobot: 15.0 },
    { cat: "KES", soal: "Saya suka mengenali zat-zat yang membahayakan kesehatan", bobot: 30.0 },
    { cat: "KES", soal: "Saya menyukai pola hidup sehat", bobot: 20.0 },
    { cat: "AGR", soal: "Saya suka mempelajari teknik bercocok tanam", bobot: 5.0 },
    { cat: "AGR", soal: "Saya suka mempelajari cara-cara pemasaran hasil pertanian", bobot: 5.0 },
    { cat: "AGR", soal: "Saya suka kegiatan bercocok tanam", bobot: 30.0 },
    { cat: "AGR", soal: "Saya suka mempelajari alat-alat pertanian", bobot: 30.0 },
    { cat: "AGR", soal: "Saya suka mempelajari ciri-ciri tanah yang subur", bobot: 10.0 },
    { cat: "AGR", soal: "Saya suka mempelajari tentang pupuk tanaman", bobot: 5.0 },
    { cat: "AGR", soal: "Saya suka merancang kegiatan wisata pertanian", bobot: 2.5 },
    { cat: "AGR", soal: "Saya suka mempelajari tentang hama tanaman", bobot: 5.0 },
    { cat: "AGR", soal: "Saya suka mempelajari zat untuk meningkatkan kualitas tanaman", bobot: 2.5 },
    { cat: "AGR", soal: "Saya suka mengenali jenis tanaman unggul", bobot: 5.0 },
    { cat: "PDK", soal: "Saya suka mempelajari cara-cara pemasaran hasil perikanan dan kelautan", bobot: 5.0 },
    { cat: "PDK", soal: "Saya suka mempelajari teknik penangkapan ikan", bobot: 15.0 },
    { cat: "PDK", soal: "Saya suka membudidayakan ikan", bobot: 30.0 },
    { cat: "PDK", soal: "Saya suka mempelajari tentang alat-alat perikanan", bobot: 30.0 },
    { cat: "PDK", soal: "Saya suka mempelajari tentang penyakit ikan", bobot: 2.5 },
    { cat: "PDK", soal: "Saya suka mempelajari tentang cara memelihara ikan", bobot: 5.0 },
    { cat: "PDK", soal: "Saya suka mengenali jenis ikan laut dan ikan air tawar", bobot: 5.0 },
    { cat: "PDK", soal: "Saya suka mempelajari cara pengawetan ikan", bobot: 2.5 },
    { cat: "PDK", soal: "Saya suka kegiatan membudidayakan hasil laut", bobot: 5.0 },
    { cat: "BDM", soal: "Saya suka menyusun rencana kegiatan", bobot: 10.0 },
    { cat: "BDM", soal: "Saya suka mempelajari surat menyurat", bobot: 2.5 },
    { cat: "BDM", soal: "Saya suka membuat laporan kegiatan", bobot: 5.0 },
    { cat: "BDM", soal: "Saya suka membuat catatan pemasukan dan pengeluaran uang", bobot: 10.0 },
    { cat: "BDM", soal: "Saya suka mempelajari pembukuan", bobot: 5.0 },
    { cat: "BDM", soal: "Saya suka mempelajari tentang perbankan", bobot: 30.0 },
    { cat: "BDM", soal: "Saya suka mengenal perpajakan", bobot: 5.0 },
    { cat: "BDM", soal: "Saya suka mempelajari kegiatan pemasaran", bobot: 2.5 },
    { cat: "BDM", soal: "Saya suka kegiatan berwirausaha", bobot: 30.0 },
    { cat: "PRW", soal: "Saya suka membuat rencana kunjungan wisata", bobot: 30.0 },
    { cat: "PRW", soal: "Saya suka menceritakan pengalaman berwisata", bobot: 10.0 },
    { cat: "PRW", soal: "Saya suka mendokumentasikan pengalaman berwisata", bobot: 15.0 },
    { cat: "PRW", soal: "Saya suka berperan sebagai pemandu wisata", bobot: 30.0 },
    { cat: "PRW", soal: "Saya menyukai kegiatan tata boga", bobot: 2.5 },
    { cat: "PRW", soal: "Saya menyukai kegiatan tata kecantikan", bobot: 5.0 },
    { cat: "PRW", soal: "Saya menyukai kegiatan perhotelan", bobot: 2.5 },
    { cat: "PRW", soal: "Saya menyukai kegiatan tata busana", bobot: 5.0 },
    { cat: "SDK", soal: "Saya suka melukis, bermusik atau menari", bobot: 30.0 },
    { cat: "SDK", soal: "Saya suka seni drama", bobot: 30.0 },
    { cat: "SDK", soal: "Saya suka seni fotografi", bobot: 15.0 },
    { cat: "SDK", soal: "Saya menyukai kegiatan seni perfilman", bobot: 10.0 },
    { cat: "SDK", soal: "Saya suka membuat karya kerajinan", bobot: 15.0 },
    { cat: "KOR", soal: "Saya suka olahraga yang bersifat pertandingan", bobot: 15.0 },
    { cat: "KOR", soal: "Saya menyukai olahraga rekreasi", bobot: 17.5 },
    { cat: "KOR", soal: "Saya suka mempelajari manfaat olahraga", bobot: 7.5 },
    { cat: "KOR", soal: "Saya suka memperhatikan perkembangan olahraga", bobot: 30.0 },
    { cat: "KOR", soal: "Saya suka mempelajari teknik olahraga", bobot: 30.0 },
]